import { createWriteStream } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import { env } from '../config/env.js';
import type { MonthlyReportDocument } from '../models/monthly-report.model.js';

interface PdfWebsite {
  name: string;
  domain: string;
}

export async function generateReportPdf(report: MonthlyReportDocument, website: PdfWebsite): Promise<string> {
  const directory = path.resolve(env.REPORT_STORAGE_PATH);
  await mkdir(directory, { recursive: true });
  const filename = `TMTR20-${slugify(website.name)}-${monthLabel(report.periodStart)}-report.pdf`;
  const absolutePath = path.join(directory, filename);
  const relativePath = path.relative(process.cwd(), absolutePath);

  await new Promise<void>((resolve, reject) => {
    const document = new PDFDocument({ margin: 50, size: 'A4' });
    const stream = createWriteStream(absolutePath);
    stream.on('finish', resolve);
    stream.on('error', reject);
    document.on('error', reject);
    document.pipe(stream);

    document.fillColor('#16324F').fontSize(24).text('TMTR20 Website Intelligence');
    document.moveDown(0.5).fillColor('#333333').fontSize(18).text(website.name);
    document.fontSize(10).fillColor('#666666').text(website.domain);
    document.text(`Reporting period: ${formatDate(report.periodStart)} to ${formatDate(report.periodEnd)}`);
    document.moveDown();

    section(document, 'KPI Summary');
    const overview = asRecord(asRecord(report.metrics).overview);
    metric(document, 'Visitors', overview.visitors);
    metric(document, 'Sessions', overview.sessions);
    metric(document, 'Page views', overview.pageViews);
    metric(document, 'Conversions', overview.conversions);
    metric(document, 'Conversion rate', `${overview.conversionRate ?? 0}%`);
    listSection(document, 'Strengths', report.strengths);
    listSection(document, 'Weaknesses', report.weaknesses);
    listSection(document, 'Opportunities', report.opportunities);
    listSection(document, 'Recommendations', report.recommendations);

    document.moveDown().fontSize(8).fillColor('#888888').text('Generated by TMTR20 Website Intelligence');
    document.end();
  });

  return relativePath;
}

function section(document: PDFKit.PDFDocument, title: string): void {
  document.moveDown().fillColor('#16324F').fontSize(14).text(title);
  document.moveDown(0.3).fillColor('#333333');
}

function metric(document: PDFKit.PDFDocument, label: string, value: unknown): void {
  document.fontSize(11).text(`${label}: ${value ?? 0}`);
}

function listSection(document: PDFKit.PDFDocument, title: string, items: string[]): void {
  section(document, title);
  if (items.length === 0) {
    document.fontSize(10).text('No items identified.');
    return;
  }
  for (const item of items) document.fontSize(10).list([item]);
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? value as Record<string, unknown> : {};
}

function formatDate(value: Date): string {
  return value.toISOString().slice(0, 10);
}

function monthLabel(value: Date): string {
  return new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric', timeZone: 'UTC' })
    .format(value)
    .replace(' ', '-');
}

function slugify(value: string): string {
  const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return slug || 'website';
}